name: Compile and post
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    container: texlive/texlive:latest
    steps:
      - uses: actions/checkout@v6
        with:
          clean: false
      - name: Install system prereqs
        run: apt-get update && apt-get install -y python3-venv openssh-client rsync
      - name: Set up venv
        run: |
          python -mvenv venv
          venv/bin/pip install -r requirements.txt
      - name: Build
        run: |
          source venv/bin/activate
          git config --global --add safe.directory /__w/website/website  # dubious ownership is okay
          make -j$((`nproc`+1)) all || ( make clean && make all )
        shell: bash
      - name: Set up SSH
        shell: bash
        run: |
          SSH_DIR="$GITHUB_WORKSPACE/.ssh"

          mkdir -p "$SSH_DIR"
          chmod 700 "$SSH_DIR"
          printf '%s\n' "${{ secrets.SSH_DEPLOY_KEY }}" > "$SSH_DIR/deploy_key"
          printf '%s\n' "${{ secrets.SSH_KNOWN_HOSTS }}" > "$SSH_DIR/known_hosts"

          cat > "$SSH_DIR"/config <<EOF
          Host target
            HostName djsutherland.ml
            User djs
            IdentityFile $SSH_DIR/deploy_key
            UserKnownHostsFile $SSH_DIR/known_hosts
            IdentitiesOnly yes
          EOF
          chmod 600 "$SSH_DIR/deploy_key" "$SSH_DIR/known_hosts" "$SSH_DIR/config"
      - name: Upload
        shell: bash
        run: |
          rsync -rlptvz \
            -e "ssh -F $GITHUB_WORKSPACE/.ssh/config -o BatchMode=yes -o ConnectTimeout=15" \
            built/ target:djsutherland.ml/
      - name: Removing stuff on failure
        if: ${{ failure() }}
        run: |
          git config --global --add safe.directory '*'
          git clean -ffdx
        # could be nice to automatically rerun from a clean checkout if it fails...
        # https://github.com/orgs/community/discussions/67654#discussioncomment-8038649
